export const AllItems = [
    {
      id: 1,
      name: 'Single Items',
    },
    {
      id: 2,
      name: 'Bundles',
    },
];

export const ShortBy = [
    {
      id: 1,
      name: 'Recently Listed',
    },
    {
      id: 2,
      name: 'Recently Created',
    },
    {
      id: 3,
      name: 'Recently Sold',
    },
    {
      id: 4,
      name: 'Recently Received',
    },
];

export const NFTs = [
    {
      id: 1,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/e2g0YukaUyw-U19qbrfUs_5C6nYI4Mu4LwFtr0ZkY5U6FvBWh2pchM-FAJFPdEpp0j6PvdmRIrjQVWsphYZtElIJMS33Fdrs_lUo=w286',
    },
    {
      id: 2,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/wlxiSWBgde1pfoj-TBoSkFEGr5XxNbk9U-Lug1QMxCpfVjTKoVIslhEuQdX4sEnY6KoLt30Ry8wPPlUgq96kYtp7CE0F6r14FbvOUw=w286',
    },
    {
      id: 3,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/SrhUiddZxhzpx8YxRUk8MpgOFTC1nQ4ho_p0peARZfrwAn69e8Umi5cCKJGdMtC6RRU2-4dD5eAG_Gy2DgQjH4Z0WDEi_8TMvC0xvQM=w286',
    },
    {
      id: 4,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/u1M2vuYZsuoXelz4NL_R3-R3TC7T1ZI9-QTZXpFda9gctEno-Qs0srHYuBUEoNxB4pz0tSWJHBfvafwloAqDHsMr46JmSJOWzNIL=w286',
    },
    {
      id: 5,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/w2hfQ4yikBJmk1UoyonR7YFubP_I_gjE8WcdpO3XeiPyCCp8hZf06p8HezZtORlYjbvUMRHbRdIRQ5TMGLrtFJHt7k1Ilp-6pzbjWQ=w286',
    },
    {
      id: 6,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/-z6WXpiD2zYjp8c3VFLkQ8a9ZPUn8jORDB0dxzl4YqPAnNLdU2OvieyvSc-EOr6K4TT1J9e6drz1EcSfay2ayRyWZSaF026oht-U6Q=w286',
    },
    {
      id: 7,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/gWdxW5Cx_kxknzAmnyMtUXrjOH_KvP0sNLHPFv_P4dAPLAQXUNcIuN5hXyGMgrgt1Wgjbqo3vtdYnVqbu-mcRwTOtmiz0kARewoN1w=w286',
    },
    {
      id: 8,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/NU_NftutgDNq99BG-5PXmJMNXfwUcSsy4nLUU2tvG1XrAwzZRRTiCDCYkO3QkC7nXxHWVn-JQXl2385cqzNat5Oo0SB6kJ0G9WyZaQ=w286',
    },
    {
      id: 9,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/pI0axF5kyNG-N3Hi1BqK7INOd9SncoQGXI-vUbyfGF8Ve0YZhgsoRJf7cWmmGrubbLc4ZdsR3lqIuWY_UkbuygewpjVTM0WH2Plmpw=w286',
    },
    {
      id: 10,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/rLV2o79eMWs5saDsKAUBu5V109qTvLYMj-rUeo2IsVKqWn3MTxTQ7DQ7V8G0JXEPugKBAdAFesL6oGRgAMH4dejGvC0ep9UPQruY=w286',
    },
    {
      id: 11,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/mZzlJFMB3krmbrCV2gHgHVn-47zc_oLBlAHC7POsC2i1mXSmV6vvgzNoC8i8J-x4kkoBmUmaLLaelSgqfqi_MbqKP_j745D3FLTv9G0=w286',
    },
    {
      id: 12,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/rHJ0zEaOzYpBXvbg41-v3G4qGW3gP4SLjf59UZ8YjhGMFdI_y0yfN0dQmNbS8EHQCR484tb0eOFKWUlFIgbV1RwAxZYBqiVNN9TABg=w286',
    },
    {
      id: 13,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/XSI5tOVmnRlXcN6KqOdFdEYOIPkPIADPujcwAX44qVes9RAulIMIeDSEDxWZXTuLCu-IOUatSVvfylJgcUhLQnhWT0cAjT3pTWBprLE=w286',
    },
    {
      id: 14,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/AiB0sVaoiP6m4LN9rsVeO5gpkfVkbFRk5oZxa4pO7Pyil8WUADuKW1bC_dLOPBk4uJlD71ZGL_XxL1oPILiF0sSY5DtX5j2GGgIKVg=w286',
    },
    {
      id: 15,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/R9tkBrLaRnIYg0Sdx-zyKt3dd8KsL8lOc7igMHB9hniVsaMNBmebUicllXqbhNk8sRYkSaodmrKAj7HotWn85wiC4kes4HOrHPr-=w286',
    },
    {
      id: 16,
      author: 'Recently Listed',
      badge: true,
      title: 'Zeno Automator: Renegade',
      price: '0.16',
      time: '3 days',
      link: 'https://opensea.io/bundles/cool-cat-legion-bundle-862018052-8R6',
      image: 'https://lh3.googleusercontent.com/vqhCyzEJT8Iik9ocVUto4ZhnL2QjVMPZOjZNfaXI_LVLBGtr4pqfmSpYquH8EN5Oz4lYH0-UC1w2wCYHEX136Kfa8Q=w286',
    },
];